### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by dvc94ch** [charleseidsness/eispice#2]
Hi!

I'm looking for a simulator that would fit well with the goals of dvc94ch/pycircuit, which is currently under heavy development.

Cheers,
David

**Comment by charleseidsness** [comment]
Hi David,

That looks like a really cool project!

eispice isn't maintained, and hasn't been for some time. I imagine it would take someone a bit effort to get it to build, and port it to Python 3.

Cheers,
Charles

**Comment by dvc94ch** [comment]
What would be needed to add ac analysis?

**Comment by charleseidsness** [comment]
It would have to be added from scratch, the ac analysis math is a lot simpler than the transient math so it probably wouldn't be a huge stretch.

**Comment by dvc94ch** [comment]
Can you recommend any literature on circuit simulation algorithms?

**Comment by charleseidsness** [comment]
I used "The Spice Book" by Vladimirescu and "Electronic Circuit & System Simulation Methods" by Pillage, Rohrer, and Visweswariah to write the algorithms for eispice. Plus the spice 3f3 users manual.
